# Generated by Django 5.2 on 2025-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
